Remove quotes on list of files to transpile in the transpiler script
With quotes on the `$artifacts_to_transpile` variable in the for loop,
the loop list is treated as a single string, so it only runs once and
fails with an error message like:
```
thread 'main' panicked at src/main.rs:31:29:
Unable to read file: target/foo-Foo.json
target/bar-Bar.json
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
because it tries to read a file named `target/foo-Foo.json\ntarget/bar-Bar.json`
instead of handling `target/foo-Foo.json` and `target/bar-Bar.json` separately.