fix: Handle revert errors from Nethermind nodes (#18431)
Updates viem to include [this
commit](https://github.com/spalladino/viem/commit/211c19497ad2af93767bcb7382cb1c092010fbf4).

This fixes viem so it can handle revert errors from Nethermind nodes.
See also https://github.com/wevm/viem/pull/4092.

This was causing validator clients to crash during startup, since it
queries the committee via the epoch cache, but if there was no committee
due to not enough validators staked, then the node would not recognise
that revert reason and fail on startup:

```
ERROR: cli Error in command execution
ERROR: cli ContractFunctionExecutionError: Execution reverted for an unknown reason.

Raw Call Arguments:
  to:    0x603bb2c05d474794ea97805e8de69bccfb3bca12
  data:  0x1cfe2878000000000000000000000000000000000000000000000000000000006917a96b

Contract Call:
  address:   0x603bb2c05d474794ea97805e8de69bccfb3bca12
  function:  getCommitteeAt(uint256 _ts)
  args:                    (1763158379)

Docs: https://viem.sh/docs/contract/simulateContract
Details: execution reverted
Version: viem@2.38.2
ContractFunctionExecutionError: Execution reverted for an unknown reason.

Raw Call Arguments:
  to:    0x603bb2c05d474794ea97805e8de69bccfb3bca12
  data:  0x1cfe2878000000000000000000000000000000000000000000000000000000006917a96b

Contract Call:
  address:   0x603bb2c05d474794ea97805e8de69bccfb3bca12
  function:  getCommitteeAt(uint256 _ts)
  args:                    (1763158379)

Docs: https://viem.sh/docs/contract/simulateContract
Details: execution reverted
Version: viem@2.38.2
    at getContractError (file:///usr/src/yarn-project/node_modules/viem/_esm/utils/errors/getContractError.js:30:12)
    at simulateContract (file:///usr/src/yarn-project/node_modules/viem/_esm/actions/public/simulateContract.js:73:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async RollupContract.getCommitteeAt (file:///usr/src/yarn-project/ethereum/dest/contracts/rollup.js:223:28)
    at async Promise.all (index 0)
    at async EpochCache.computeCommittee (file:///usr/src/yarn-project/epoch-cache/dest/epoch_cache.js:150:51)
    at async EpochCache.getCommittee (file:///usr/src/yarn-project/epoch-cache/dest/epoch_cache.js:126:27)
    at async EpochCache.filterInCommittee (file:///usr/src/yarn-project/epoch-cache/dest/epoch_cache.js:260:31)
    at async ValidatorClient.start (file:///usr/src/yarn-project/validator-client/dest/validator.js:136:29)
    at async SequencerClient.start (file:///usr/src/yarn-project/sequencer-client/dest/client/sequencer-client.js:110:9)
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
... (646 lines left)
```

See
[here](https://github.com/AztecProtocol/aztec-packages/blob/3d9dccdae863a72c0c4ba91019e504d778f21e3c/yarn-project/ethereum/src/contracts/rollup.ts#L365-L370)
for reference.