feat!: disconnect from peers on heartbeat (#15826)
These changes were made as an attempt to deflake e2e/preferred_gossip
test.

PR brings that peers are disconnected on a heartbeat instead of
immediately.

I still cannot point to the exact cause of the issues when disconnecting
peers, but it all points to some race condition or not handling errors
correctly within libp2p or gossipsub.
For example, this is the error I was seeing in tests, which I don't see
after applying this fix:

```
CodeError: unexpected end of input
    at DefaultUpgrader._encryptOutbound (/workspaces/aztec-packages/yarn-project/node_modules/libp2p/src/upgrader.ts:682:13)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at DefaultUpgrader.upgradeOutbound (/workspaces/aztec-packages/yarn-project/node_modules/libp2p/src/upgrader.ts:292:13)
    at TCP.dial (/workspaces/aztec-packages/yarn-project/node_modules/@libp2p/tcp/src/index.ts:181:18)
    at DefaultTransportManager.dial (/workspaces/aztec-packages/yarn-project/node_modules/libp2p/src/transport-manager.ts:116:14)
    at Job.queue.add.peerId.peerId [as fn] (/workspaces/aztec-packages/yarn-project/node_modules/libp2p/src/connection-manager/dial-queue.ts:236:26)
    at raceSignal (/workspaces/aztec-packages/yarn-project/node_modules/race-signal/src/index.ts:46:12)
    at Job.run (/workspaces/aztec-packages/yarn-project/node_modules/@libp2p/utils/src/queue/job.ts:79:22) {
  code: 'ERR_ENCRYPTION_FAILED',
  props: {}
```